import { useState } from "react";
import { Link } from "react-router-dom";
import api from "../api/client";
import { Field, Shell } from "./shared";

export function ForgotPassword() {
  const [email, setEmail] = useState(""); const [message, setMessage] = useState(""); const [resetToken, setResetToken] = useState(""); const [error, setError] = useState(""); const [submitting, setSubmitting] = useState(false);
  const submit = async (event) => { event.preventDefault(); setError(""); setMessage(""); setSubmitting(true); try { const response = await api.post("/auth/forgot-password", { email }); setMessage(response.data?.message || "Password reset instructions have been generated."); if (response.data?.data?.reset_token) setResetToken(response.data.data.reset_token); } catch (requestError) { setError(requestError.response?.data?.message || "Unable to request password reset."); } finally { setSubmitting(false); } };
  return <Shell><main className="auth-screen"><div className="auth-brand"><span>🔑</span><strong>🚨 Ajali! Security</strong></div><h1>Reset Password</h1><p className="auth-sub">Enter your registered email address. We will generate a secure link to reset your account password.</p>{message ? <div style={{ textAlign: "center", marginTop: "20px" }}><p style={{ color: "#16a34a", marginBottom: "16px", fontWeight: "600" }}>{message}</p>{resetToken && <div style={{ background: "#f3f4f6", padding: "12px", borderRadius: "8px", marginBottom: "16px" }}><p style={{ fontSize: "12px", color: "#555", marginBottom: "8px" }}>Development Mode Token:</p><Link className="btn btn-primary btn-block" to={`/reset-password?token=${encodeURIComponent(resetToken)}`}>Click Here to Set New Password</Link></div>}<Link className="btn btn-outline btn-block" to="/login">Return to Log in</Link></div> : <form onSubmit={submit}>{error && <p className="form-error" role="alert">{error}</p>}<Field label="Email Address"><input className="input" type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="jane@example.com" required /></Field><button className="btn btn-primary btn-block btn-lg" type="submit" disabled={submitting}>{submitting ? "Sending…" : "Send Reset Instructions"}</button><p className="auth-switch">Remember your password? <Link to="/login">Log in</Link></p></form>}<div className="home-indicator" aria-hidden="true"><div className="home-indicator__pill" /></div></main></Shell>;
}
