import { useState } from "react";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import api from "../api/client";
import { Field, Shell } from "./shared";

export function ResetPassword() {
  const navigate = useNavigate(); const [searchParams] = useSearchParams(); const [token, setToken] = useState(searchParams.get("token") || ""); const [password, setPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState(""); const [error, setError] = useState(""); const [successMsg, setSuccessMsg] = useState(""); const [submitting, setSubmitting] = useState(false);
  const submit = async (event) => { event.preventDefault(); setError(""); if (password.length < 8) return setError("Password must be at least 8 characters long."); if (password !== confirmPassword) return setError("Passwords do not match."); setSubmitting(true); try { const response = await api.post("/auth/reset-password", { token, password }); setSuccessMsg(response.data?.message || "Password reset successfully!"); setTimeout(() => navigate("/login"), 2000); } catch (requestError) { setError(requestError.response?.data?.message || "Unable to reset password. Token may be expired."); } finally { setSubmitting(false); } };
  return <Shell><main className="auth-screen"><div className="auth-brand"><span>🔒</span><strong>🚨 Ajali! Security</strong></div><h1>Create New Password</h1><p className="auth-sub">Please enter your reset token and select a new secure password of at least 8 characters.</p>{successMsg ? <div style={{ textAlign: "center", marginTop: "20px" }}><p style={{ color: "#16a34a", fontWeight: "600", marginBottom: "16px" }}>{successMsg}</p><p style={{ fontSize: "14px", color: "#666" }}>Redirecting to login…</p></div> : <form onSubmit={submit}>{error && <p className="form-error" role="alert">{error}</p>}<Field label="Reset Token"><input className="input" value={token} onChange={(event) => setToken(event.target.value)} placeholder="Paste reset token" required /></Field><Field label="New Password"><input className="input" type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="At least 8 characters" required /></Field><Field label="Confirm New Password"><input className="input" type="password" value={confirmPassword} onChange={(event) => setConfirmPassword(event.target.value)} placeholder="Confirm password" required /></Field><button className="btn btn-primary btn-block btn-lg" type="submit" disabled={submitting}>{submitting ? "Updating password…" : "Update Password"}</button><p className="auth-switch">Cancel and return to <Link to="/login">Log in</Link></p></form>}<div className="home-indicator" aria-hidden="true"><div className="home-indicator__pill" /></div></main></Shell>;
}
